export const posts = [
    {
      id: 1,
      title: 'Boost your conversion rate',
      href: '#',
      description: 'Illo sint voluptas. Error voluptates culpa eligendi. Hic vel totam vitae illo. Non aliquid explicabo necessitatibus unde. Sed exercitationem placeat consectetur nulla deserunt vel. Iusto corrupti dicta.',
      date: 'Mar 16, 2020',
      datetime: '2020-03-16',
      category: { title: 'Marketing', href: '#' },
      author: {
        name: 'Michael Foster',
        role: 'Co-Founder / CTO',
        href: '#',
        imageUrl: 'https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
      },
    },
    {
      id: 2,
      title: 'Improve your website design',
      href: '#',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Sed eget mi euismod, eleifend tellus eget, rhoncus lacus.',
      date: 'Apr 24, 2020',
      datetime: '2020-04-24',
      category: { title: 'Web Design', href: '#' },
      author: {
        name: 'Jennifer Carter',
        role: 'Lead Designer',
        href: '#',
        imageUrl: 'https://images.unsplash.com/photo-1546456073-6712f79251bb?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
      },
    },
    {
        id: 2,
        title: '10 Tips for Effective Social Media Marketing',
        href: '#',
        description: 'Discover strategies to boost your brand\'s presence on social media platforms. From content creation to engagement, learn the secrets of effective social media marketing.',
        date: 'May 12, 2020',
        datetime: '2020-05-12',
        category: { title: 'Social Media', href: '#' },
        author: {
          name: 'Jessica Reynolds',
          role: 'Social Media Manager',
          href: '#',
          imageUrl: 'https://images.unsplash.com/photo-1550549651-32385fe94ff7?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
        },
      },
      {
        id: 3,
        title: 'The Future of E-commerce: Trends to Watch',
        href: '#',
        description: 'Explore the latest trends shaping the future of e-commerce. From AI-powered personalization to augmented reality shopping experiences, discover what lies ahead.',
        date: 'Jun 28, 2020',
        datetime: '2020-06-28',
        category: { title: 'E-commerce', href: '#' },
        author: {
          name: 'Alex Turner',
          role: 'E-commerce Strategist',
          href: '#',
          imageUrl: 'https://images.unsplash.com/photo-1591721834749-87f32a6dd7b4?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
        },
      },
      // Add 6 more dummy elements here
      {
        id: 4,
        title: 'Mastering SEO: A Comprehensive Guide',
        href: '#',
        description: 'Unlock the secrets of search engine optimization (SEO) with this comprehensive guide. Learn best practices, tips, and tricks to improve your website\'s search ranking.',
        date: 'Aug 15, 2020',
        datetime: '2020-08-15',
        category: { title: 'SEO', href: '#' },
        author: {
          name: 'Ryan Mitchell',
          role: 'SEO Specialist',
          href: '#',
          imageUrl: 'https://images.unsplash.com/photo-1554290710-95aa804ef6eb?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
        },
      },
      {
        id: 5,
        title: 'Creating Engaging Content: Tips for Success',
        href: '#',
        description: 'Learn how to captivate your audience with compelling content. Explore content creation strategies, storytelling techniques, and the art of crafting engaging posts.',
        date: 'Sep 22, 2020',
        datetime: '2020-09-22',
        category: { title: 'Content Marketing', href: '#' },
        author: {
          name: 'Emily Rodriguez',
          role: 'Content Creator',
          href: '#',
          imageUrl: 'https://images.unsplash.com/photo-1546647925-12e5160bf942?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
        },
      },
      {
        id: 6,
        title: 'Harnessing the Power of Email Marketing',
        href: '#',
        description: 'Discover effective email marketing strategies to nurture leads and drive conversions. From personalized campaigns to automation, unlock the potential of email marketing.',
        date: 'Oct 10, 2020',
        datetime: '2020-10-10',
        category: { title: 'Email Marketing', href: '#' },
        author: {
          name: 'Daniel Turner',
          role: 'Email Marketing Specialist',
          href: '#',
          imageUrl: 'https://images.unsplash.com/photo-1541059572726-610c4ef05f7d?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80',
        },
      },
    // Repeat the pattern for more posts...
    // Add 8 more dummy elements here
  ];
  